version: '3'

services:
  gym-point-api:
    build: .
    container_name: gym-point-api
    volumes:
      - .:/home/jura/Projetos/git.rocketseat/gym-point
      - /home/jura/Projetos/git.rocketseat/gym-point/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - gym-point-postgres
    networks:
      - gym-point-network
    command: sh /home/jura/Projetos/git.rocketseat/gym-point/start-enviroment.sh
  gym-point-postgres:
    image: postgres
    container_name: gym-point-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - gym-point-postgres-data:/data
    ports:
      - "5432:5432"
    networks:
      - gym-point-network
volumes:
  gym-point-postgres-data:

networks:
  gym-point-network:
    driver: bridge
